In [4]:
import numpy as np

# Create a 1D NumPy array
x = np.array([1, 2, 3, 4, 5])

# Create a 2D NumPy array
y = np.array([[1, 2, 3], [4, 5, 6]])

print(x)

print(y)




[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [6]:
m = np.mean(x)
print(m)  # Output: 3.0


3.0


In [7]:
# Find the standard deviation of an array
s = np.std(x)
print(s)  # Output: 1.4142135623730951

1.4142135623730951


In [8]:
# We can reshape an array
x_reshaped = x.reshape((5, 1))
print(x_reshaped) 

[[1]
 [2]
 [3]
 [4]
 [5]]
