In [1]:
import numpy as np

# Create a 1D NumPy array
x = np.array([1, 2, 3, 4, 5])

# Create a 2D NumPy array
y = np.array([[1, 2, 3], [4, 5, 6]])

print(x)

print(y)




[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [6]:
m = np.mean(x)
print(m)  # Output: 3.0


3.0


In [7]:
# Find the standard deviation of an array
s = np.std(x)
print(s)  # Output: 1.4142135623730951

1.4142135623730951


In [8]:
# We can reshape an array
x_reshaped = x.reshape((5, 1))
print(x_reshaped) 

[[1]
 [2]
 [3]
 [4]
 [5]]


In [9]:
# We can transpose an array
x_transposed = x.T
print(x_transposed)

[1 2 3 4 5]


In [4]:
# Now we can see a few basic examples of Pandas library

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/sanjibsinha/Machine-Learning-Primer/main/world_internet_user.csv', encoding = 'unicode_escape', engine ='python')
df.head()

Country   Region  Population  Internet Users  % of Population
0          _World      NaN  7920539977      5424080321            68.48
1      Afganistan     Asia    40403518         9237489            22.86
2         Albania   Europe     2872758         2191467            76.28
3         Algeria   Africa    45150879        37836425            83.80
4  American Samoa  Oceania       54995           34800            63.28

In [7]:
import pandas as pd
data = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(data, columns=['a', 'b', 'c'])
df


a  b  c
0  1  2  3
1  4  5  6

In [8]:
# To access a column of the DataFrame
import pandas as pd
data = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(data, columns=['a', 'b', 'c'])
# df
col_b = df['b']
print(col_b)

0    2
1    5
Name: b, dtype: int64


In [10]:
# To access a row of the DataFrame
import pandas as pd
data = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(data, columns=['a', 'b', 'c'])
row_0 = df.iloc[1]
print(row_0)

a    4
b    5
c    6
Name: 1, dtype: int64
