In [25]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model, model_selection
import matplotlib.pyplot as plt

df = pd.read_csv('https://raw.githubusercontent.com/sanjibsinha/Machine-Learning-Primer/main/world_internet_user.csv', encoding = 'unicode_escape', engine ='python')
df.head()

Country   Region  Population  Internet Users  % of Population
0          _World      NaN  7920539977      5424080321            68.48
1      Afganistan     Asia    40403518         9237489            22.86
2         Albania   Europe     2872758         2191467            76.28
3         Algeria   Africa    45150879        37836425            83.80
4  American Samoa  Oceania       54995           34800            63.28

In [7]:
df.drop(['Country', 'Region', 'Population'], axis=1, inplace=True)

In [8]:
df

Internet Users  % of Population
0        5424080321            68.48
1           9237489            22.86
2           2191467            76.28
3          37836425            83.80
4             34800            63.28
..              ...              ...
238            6200            56.71
239           28000             4.58
240         8353377            27.00
241         9870427            52.17
242         8400000            55.66

[243 rows x 2 columns]

In [9]:
model = linear_model.LinearRegression()
model.fit(df[['Internet Users']],df['% of Population'])

LinearRegression()

In [10]:
model.coef_

array([6.33494466e-10])

In [11]:
model.intercept_

69.89283024800785

In [15]:
model.predict([[3823432]])

/home/ss/.local/lib/python3.8/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([69.89525237])

In [16]:
import pickle

In [17]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [18]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [19]:
mp.coef_

array([6.33494466e-10])

In [20]:
mp.intercept_

69.89283024800785

In [22]:
mp.predict([[3823432]])

/home/ss/.local/lib/python3.8/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([69.89525237])