<a href="https://colab.research.google.com/github/sanjibsinha/Machine-Learning-Primer/blob/main/tf_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [3]:
# Create two constant tensors
tensor_a = tf.constant([[1, 2],
                        [3, 4]])
tensor_b = tf.constant([[5, 6],
                        [7, 8]])

# Add the tensors
tensor_sum = tensor_a + tensor_b

# Print the tensors and their sum
print("Tensor A:")
print(tensor_a)
print("\nTensor B:")
print(tensor_b)
print("\nSum of Tensor A and Tensor B:")
print(tensor_sum)

Tensor A:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Tensor B:
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)

Sum of Tensor A and Tensor B:
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
